### ISSUE TITLE
[feature] add method to extract the Mutex from the MutexGuard

### ISSUE THREAD

**Issue by dignifiedquire** [stjepang/async-mutex#1]
This is useful in the implementation of other primitives like `Condvar`, when one wants to avoid triggering the `drop` implementation on `MutexGuard`.

**Comment by stjepang** [comment]
Can you say more, I'm not sure I understand? Would that be something like:

```rust
impl<T> MutexGuard<'_, T> {
   fn mutex(&self) -> &Mutex<T>;
}
```

**Comment by dignifiedquire** [comment]
This is the equivalent function in the std lib

https://github.com/rust-lang/rust/blob/master/src/libstd/sync/mutex.rs#L465

and in async-std

https://github.com/async-rs/async-std/blob/master/src/sync/mutex.rs#L292

used like this:

https://github.com/async-rs/async-std/blob/master/src/sync/condvar.rs#L123

**Comment by stjepang** [comment]
How about this?

```rust
impl<'a, T> MutexGuard<'a, T> {
    fn source(guard: &Self) -> &'a Mutex<T>;
}
```

The reason why the method doesn't take `&self` is because `MutexGuard` is a smart pointer and smart pointers don't implement such methods.

For consistency, I'd also then add a similar `source()` method for `LockGuard` in the `async-lock` crate.

I was torn between names `source()`, `parent()`, `origin()`, and `mutex()`/`lock()` - any preferences there?

**Comment by dignifiedquire** [comment]
Maybe `inner_mutex()`/`inner_lock()`?
